import { useEffect, useRef } from "react";
import { LngLatBounds, Map as MapLibreMap, NavigationControl, type Map as MapType } from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css";
import { getNode } from "../lib/YP_worldmap";

export type DashboardRoute = { origin_node_id:string; origin_name:string; destination_node_id:string; destination_name:string; mode:string };
const COLORS:Record<string,string>={sea:"#31A8FF",rail:"#32E0A1",air:"#B388FF",road:"#FFB84D",truck:"#FFB84D"};
export function YPDashboardNetworkMap({routes,visibleModes}:{routes:DashboardRoute[];visibleModes:string[]}) {
  const el=useRef<HTMLDivElement>(null), map=useRef<MapType|null>(null);
  useEffect(()=>{if(!el.current||map.current)return;map.current=new MapLibreMap({container:el.current,style:"https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json",center:[25,30],zoom:1.25,renderWorldCopies:false});map.current.addControl(new NavigationControl({showCompass:false}),"top-right");return()=>{map.current?.remove();map.current=null}},[]);
  useEffect(()=>{const m=map.current;if(!m)return;const draw=()=>{["yp-routes","yp-nodes"].forEach(id=>{if(m.getLayer(id))m.removeLayer(id)});["yp-route-source","yp-node-source"].forEach(id=>{if(m.getSource(id))m.removeSource(id)});const filtered=routes.filter(r=>visibleModes.includes(r.mode==="road"?"truck":r.mode));const bounds=new LngLatBounds();const lines=filtered.map(r=>{const a=getNode(r.origin_node_id),b=getNode(r.destination_node_id);bounds.extend(a);bounds.extend(b);return{type:"Feature" as const,properties:{color:COLORS[r.mode]??"#79A8D8"},geometry:{type:"LineString" as const,coordinates:[a,b]}}});m.addSource("yp-route-source",{type:"geojson",data:{type:"FeatureCollection",features:lines}});m.addLayer({id:"yp-routes",type:"line",source:"yp-route-source",paint:{"line-color":["get","color"],"line-width":2.2,"line-opacity":.82,"line-dasharray":[1.2,2]}});const nodes=new Map<string,{point:[number,number],color:string}>();filtered.forEach(r=>{nodes.set(r.origin_node_id,{point:getNode(r.origin_node_id),color:COLORS[r.mode]});nodes.set(r.destination_node_id,{point:getNode(r.destination_node_id),color:COLORS[r.mode]})});const points=[...nodes.entries()].map(([id,n])=>({type:"Feature" as const,properties:{id,color:n.color},geometry:{type:"Point" as const,coordinates:n.point}}));m.addSource("yp-node-source",{type:"geojson",data:{type:"FeatureCollection",features:points}});m.addLayer({id:"yp-nodes",type:"circle",source:"yp-node-source",paint:{"circle-radius":4.5,"circle-color":["get","color"],"circle-stroke-width":1.6,"circle-stroke-color":"#fff"}});if(!bounds.isEmpty())m.fitBounds(bounds,{padding:48,maxZoom:4.6})};if(m.isStyleLoaded())draw();else m.once("load",draw)},[routes,visibleModes]);
  return <div ref={el} className="yp-dashboard-network-map"/>;
}
